server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javasept
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

address: Virginia YML
welcome:
  msg: Hello World YML